# Generated by Django 3.1.2 on 2020-11-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='portfolio/image')),
                ('InstaURL', models.URLField()),
                ('Gmail', models.CharField(max_length=100)),
            ],
        ),
    ]
